#!/bin/bash

node -e '
var os = require("os");

var status = function () {
  var loadavg = os.loadavg();
  return {
    // cpu:
    uptime: os.uptime(), // in ms
    totalmem: os.totalmem(), // in byte
    freemem: os.freemem(), // in byte
    load1: loadavg[0],
    load5: loadavg[1],
    load15: loadavg[2]
  };
};

console.log(JSON.stringify(status()));'
