#!/bin/sh

export ENABLE_NODE_LOG=NO

DIR=$(cd "$(dirname "$0")"; pwd)
GET_NODE_EXE=$DIR/get_node_exe
NODE_EXE=`$GET_NODE_EXE`

$NODE_EXE -e '
var os = require("os");
console.log("%s/%s/%s/%s/%s", os.type(), os.hostname(), os.platform(), os.arch(), os.release());
'
