#!/bin/bash
DIR=$WORK_DIR

if [ -z "$DIR" ]; then
   echo '请配置 WORK_DIR 环境变量'
   exit 1
fi

kill -USR2 $1

for ((i=1; i<=3; i ++))
do
    sleep 2
    FILE_NAME=`ls -rt $DIR/heapdump-*.*.heapsnapshot | tail -1`

    if [ -n "$FILE_NAME" ]; then
	  echo 'heapdump文件路径:'$FILE_NAME
	  echo '等待文件写入30s.'
	  break
    fi
done



