#!/bin/bash

NODE_KILL=`which node-kill`

if [ -f "$HOME/.nodepath" ]; then
  NODE_KILL=`cat $HOME/.nodepath`/node-kill;
fi

$NODE_KILL --v8-options --trace_gc --trace_gc_nvp --trace_fragmentation --trace_gc_verbose --pid=$1
