#!/bin/bash

UPLOADER=`which uploader`

if [ -f "$HOME/.nodepath" ]; then
  UPLOADER=`cat $HOME/.nodepath`/uploader
fi

FULL_PATH=$2
TARGET_PATH=$2

GZIP=`which gzip`

if [ $GZIP ]; then
  $GZIP -c $FULL_PATH > $FULL_PATH".gz"
  TARGET_PATH=$FULL_PATH".gz"
fi

#uploader server filepath token id
ENABLE_NODE_LOG=NO $UPLOADER $1 $TARGET_PATH $3 $4
