#!/bin/sh

export ENABLE_NODE_LOG=NO

DIR=$(cd "$(dirname "$0")"; pwd)
GET_NODE_EXE=$DIR/get_node_exe
NODE_EXE=`$GET_NODE_EXE`

FULL_PATH=$2
TARGET_PATH=$2

filesize=`ls -l $FULL_PATH|awk '{print $5}'`

if [ "$filesize" = 0 ]; then
  echo '空文件'
  exit 1
fi

GZIP=`which gzip`

if [ $GZIP ] && [ -f "$FULL_PATH" ]; then
  $GZIP -c $FULL_PATH > $FULL_PATH".gz"
  TARGET_PATH=$FULL_PATH".gz"
fi

UPLOADER=$DIR/uploader.js

#uploader server filepath token id
$NODE_EXE "$UPLOADER" $1 $TARGET_PATH $3 $4 $5 $6
