#!/bin/bash

UPLOADER=`which uploader`

if [ -f "$HOME/.nodepath" ]; then
  UPLOADER=`cat $HOME/.nodepath`/uploader
fi

FULL_PATH=$2
TARGET_PATH=$2

FILE=`echo $FULL_PATH |awk -F "\/" '{print $NF}'`
DIR=`dirname $FULL_PATH`
GZIP=`which gzip`

if [ $GZIP ]; then
  cd $DIR
  $GZIP $FILE
  TARGET_PATH=$FULL_PATH".gz"
fi

# ./uploader server filepath token id
$UPLOADER $1 $TARGET_PATH $3 $4
